# Generated by Django 4.0.6 on 2022-09-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_path', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('mailing_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('fax', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('formal_name', models.CharField(max_length=20)),
                ('fin_begin', models.DateField()),
                ('books_begin', models.DateField()),
                ('fin_end', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tally_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_alias', models.CharField(max_length=255)),
                ('group_under', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255, null=True)),
                ('gross_profit', models.CharField(max_length=255, null=True)),
                ('sub_ledger', models.CharField(max_length=255)),
                ('debit_credit', models.CharField(max_length=255)),
                ('calculation', models.CharField(max_length=255)),
                ('invoice', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.companies')),
            ],
        ),
        migrations.CreateModel(
            name='transactiontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Vouchertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vouchertype', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tally_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('under', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('bank_details', models.CharField(max_length=20, null=True)),
                ('pan_no', models.CharField(max_length=100, null=True)),
                ('registration_type', models.CharField(max_length=100, null=True)),
                ('gst_uin', models.CharField(max_length=100, null=True)),
                ('set_alter_gstdetails', models.CharField(max_length=100, null=True)),
                ('opening_blnc', models.IntegerField(null=True)),
                ('set_odl', models.CharField(max_length=255, null=True)),
                ('ac_holder_nm', models.CharField(max_length=255, null=True)),
                ('acc_no', models.CharField(max_length=255, null=True)),
                ('ifsc_code', models.CharField(max_length=255, null=True)),
                ('swift_code', models.CharField(max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('SA_cheque_bk', models.CharField(max_length=20, null=True)),
                ('Echeque_p', models.CharField(max_length=20, null=True)),
                ('SA_chequeP_con', models.CharField(max_length=20, null=True)),
                ('type_of_ledger', models.CharField(max_length=100, null=True)),
                ('rounding_method', models.CharField(max_length=100, null=True)),
                ('rounding_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('type_duty_tax', models.CharField(max_length=100, null=True)),
                ('tax_type', models.CharField(max_length=100, null=True)),
                ('valuation_type', models.CharField(max_length=100, null=True)),
                ('rate_per_unit', models.IntegerField(blank=True, default=None, null=True)),
                ('percentage_of_calcution', models.CharField(max_length=100, null=True)),
                ('rond_method', models.CharField(max_length=100, null=True)),
                ('rond_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('gst_applicable', models.CharField(max_length=100, null=True)),
                ('setalter_gstdetails', models.CharField(max_length=20, null=True)),
                ('type_of_supply', models.CharField(max_length=100, null=True)),
                ('assessable_value', models.CharField(max_length=100, null=True)),
                ('appropriate_to', models.CharField(max_length=100, null=True)),
                ('method_of_calculation', models.CharField(max_length=100, null=True)),
                ('balance_billbybill', models.CharField(max_length=100, null=True)),
                ('credit_period', models.CharField(max_length=100, null=True)),
                ('creditdays_voucher', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.companies')),
                ('grp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.tally_group')),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('Partyname', models.CharField(max_length=255)),
                ('salesledger', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('particualrs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.tally_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.IntegerField()),
                ('no', models.IntegerField()),
                ('partyname', models.CharField(max_length=225)),
                ('purchaseledger', models.CharField(max_length=225)),
                ('itemname', models.CharField(max_length=225)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('particualrs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.tally_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('particualrs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.tally_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instno', models.IntegerField()),
                ('instdate', models.DateField()),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.particulars')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.account')),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.tally_ledger')),
                ('transactiontype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.transactiontype')),
                ('vouchertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.vouchertype')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_Vouchers_app.tally_ledger'),
        ),
    ]
